# this is a template to factorize the service definitions
x-services-templates:
    worker_base: &worker_base
        build:
            context: services/php
            target: worker
            cache_from:
                - "${REGISTRY:-}/worker:cache"
        depends_on:
            - postgres
            #- rabbitmq
        user: "${USER_ID}:${USER_ID}"
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        labels:
          - "docker-starter.worker.${PROJECT_NAME}=true"
        environment:
          - HOME=/home/app
        profiles:
            - default
            - worker

# services:
#    worker_messenger:
#        <<: *worker_base
#        command: php -d memory_limit=1G /var/www/application/bin/console messenger:consume async --memory-limit=128M
