#!/bin/bash

# Function to update the fpm configuration to make the service environment variables available
function set_env_variable() {
    if [ -z "$2" ]; then
        return
    fi

    # Add variable
    echo "fastcgi_param $1 $2;" >> /etc/nginx/environments
}

if [ -e /etc/nginx/environments ]
then
    rm /etc/nginx/environments
fi

touch /etc/nginx/environments

# Grep for variables that look like docker set them (_PORT_)
for _curVar in `env | grep myapp | awk -F = '{print $1}'`;do
    set_env_variable ${_curVar} ${!_curVar}
done

exec nginx
