name: Push docker image to registry

"on":
  push:
    branches: ["main", "feat/registry-docker"]

permissions:
  contents: read
  packages: write

env:
  # Fix for symfony/color detection. We know GitHub Actions can handle it
  DS_REGISTRY: "ghcr.io/jolicode/docker-starter-cache"
  DS_PHP_VERSION: "8.3"

jobs:
  push-images:
    name: Push image to registry
    runs-on: ubuntu-latest
    env:
      DS_PHP_VERSION: "8.3"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v4

      - name: setup-castor
        uses: castor-php/setup-castor@v0.1.0

      - name: Log in to registry
        shell: bash
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: "Build and start the infrastructure"
        run: "castor docker:push"
